### ISSUE TITLE
broken windows build

### ISSUE THREAD

**Issue by grlee77** [conda-forge/pyfftw-feedstock#26]
The recently merged windows PR (#23) is failing to build the windows packages.

There is a complaint about an absolute path being found in the `pyFFTW.egg-info/SOURCES.txt`
https://ci.appveyor.com/project/conda-forge/pyfftw-feedstock/build/job/jxmffjos8pc21sik#L855

see related issue:  pyFFTW/pyFFTW#249

**Comment by jakirkham** [comment]
Strange that it didn't come up in the PR builds. 😕
